version: '3.9'

services:
  postgresql:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    restart: on-failure
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/postgres
      - --username=postgres
      - --password=password
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  db-service:
    image: collect_invest/db_service
    depends_on:
      - postgresql
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/imageStorage:/liquibase/changelog:/app/src/main/resources/ImageStorage/
    networks:
      - backend

  financial-service:
    image: collect_invest/financial_service
    depends_on:
      - db-service
    restart: on-failure
    ports:
      - "7777:7777"
    networks:
      - backend

  api-service:
    image: collect_invest/api_service
    depends_on:
      - db-service
    restart: on-failure
    ports:
      - "1111:1111"
    networks:
      - backend

  collectible-service:
    image: collect_invest/collectible_service
    depends_on:
      - db-service
    restart: on-failure
    ports:
      - "3937:3937"
    networks:
      - backend

  user-service:
    image: collect_invest/user_service
    depends_on:
      - db-service
    restart: on-failure
    ports:
      - "9999:9999"
    networks:
      - backend

volumes:
  postgresql_data:

networks:
  backend: